version: "3.8"
services:
  web:
    build: .
    command: craft serve -p 8000 -b 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.docker
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    volumes:
      - test-sql-2:/var/lib/mysql:delegated
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: democenter_db
      MYSQL_USER: nylasuser
      MYSQL_PASSWORD: secret
      MYSQL_TCP_PORT: 3307


volumes:
  test-sql-2:
